//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCup.DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCup.DataLayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string BtnApply {
            get {
                return ResourceManager.GetString("BtnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Detail Statistics.
        /// </summary>
        public static string BtnDetailStatistics {
            get {
                return ResourceManager.GetString("BtnDetailStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string BtnMatches {
            get {
                return ResourceManager.GetString("BtnMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string BtnNo {
            get {
                return ResourceManager.GetString("BtnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string BtnPlayers {
            get {
                return ResourceManager.GetString("BtnPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Rankings.
        /// </summary>
        public static string BtnPrintRankings {
            get {
                return ResourceManager.GetString("BtnPrintRankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        public static string BtnRankCard {
            get {
                return ResourceManager.GetString("BtnRankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string BtnRankGoal {
            get {
                return ResourceManager.GetString("BtnRankGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BtnRemove {
            get {
                return ResourceManager.GetString("BtnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Favorite Match.
        /// </summary>
        public static string BtnSetMatch {
            get {
                return ResourceManager.GetString("BtnSetMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Favorite Team.
        /// </summary>
        public static string BtnSetTeam {
            get {
                return ResourceManager.GetString("BtnSetTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Rankings.
        /// </summary>
        public static string BtnShowRankings {
            get {
                return ResourceManager.GetString("BtnShowRankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string BtnTeamStatistics {
            get {
                return ResourceManager.GetString("BtnTeamStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string BtnYes {
            get {
                return ResourceManager.GetString("BtnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ImgArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgArrowRight {
            get {
                object obj = ResourceManager.GetObject("ImgArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgDefault {
            get {
                object obj = ResourceManager.GetObject("ImgDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImgStar {
            get {
                object obj = ResourceManager.GetObject("ImgStar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woman.
        /// </summary>
        public static string TextCategoryFemale {
            get {
                return ResourceManager.GetString("TextCategoryFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string TextCategoryMale {
            get {
                return ResourceManager.GetString("TextCategoryMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ranking Type.
        /// </summary>
        public static string TextCategoryOption {
            get {
                return ResourceManager.GetString("TextCategoryOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the data loading method.
        /// </summary>
        public static string TextDataLoad {
            get {
                return ResourceManager.GetString("TextDataLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        public static string TextExit {
            get {
                return ResourceManager.GetString("TextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string TextFavorites {
            get {
                return ResourceManager.GetString("TextFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid photo formats: JPG..
        /// </summary>
        public static string TextImageFormat {
            get {
                return ResourceManager.GetString("TextImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore statistics from the 2018 Men’s and 2019 Women’s World Cups..
        /// </summary>
        public static string TextIntro {
            get {
                return ResourceManager.GetString("TextIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string TextLanguageENG {
            get {
                return ResourceManager.GetString("TextLanguageENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string TextLanguageHRV {
            get {
                return ResourceManager.GetString("TextLanguageHRV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string TextLoading {
            get {
                return ResourceManager.GetString("TextLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string TextMarkAppearances {
            get {
                return ResourceManager.GetString("TextMarkAppearances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away Team.
        /// </summary>
        public static string TextMarkAwayTeam {
            get {
                return ResourceManager.GetString("TextMarkAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capetain.
        /// </summary>
        public static string TextMarkCapetain {
            get {
                return ResourceManager.GetString("TextMarkCapetain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Cards.
        /// </summary>
        public static string TextMarkCards {
            get {
                return ResourceManager.GetString("TextMarkCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TextMarkDate {
            get {
                return ResourceManager.GetString("TextMarkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string TextMarkGoals {
            get {
                return ResourceManager.GetString("TextMarkGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Team.
        /// </summary>
        public static string TextMarkHomeTeam {
            get {
                return ResourceManager.GetString("TextMarkHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string TextMarkImg {
            get {
                return ResourceManager.GetString("TextMarkImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TextMarkLocation {
            get {
                return ResourceManager.GetString("TextMarkLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextMarkName {
            get {
                return ResourceManager.GetString("TextMarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string TextMarkPosition {
            get {
                return ResourceManager.GetString("TextMarkPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string TextMarkShirtNumber {
            get {
                return ResourceManager.GetString("TextMarkShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string TextMarkVisitors {
            get {
                return ResourceManager.GetString("TextMarkVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Favorite Match Set.
        /// </summary>
        public static string TextNoMatchSet {
            get {
                return ResourceManager.GetString("TextNoMatchSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Favorite Team Set.
        /// </summary>
        public static string TextNoTeamSet {
            get {
                return ResourceManager.GetString("TextNoTeamSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string TextOptionAPI {
            get {
                return ResourceManager.GetString("TextOptionAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Category.
        /// </summary>
        public static string TextOptionCategory {
            get {
                return ResourceManager.GetString("TextOptionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string TextOptionJSON {
            get {
                return ResourceManager.GetString("TextOptionJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Language.
        /// </summary>
        public static string TextOptionLanguage {
            get {
                return ResourceManager.GetString("TextOptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Screen Size.
        /// </summary>
        public static string TextOptionScreenSize {
            get {
                return ResourceManager.GetString("TextOptionScreenSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Favorite!.
        /// </summary>
        public static string TextPlayerSelector {
            get {
                return ResourceManager.GetString("TextPlayerSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Ranking Criteria.
        /// </summary>
        public static string TextRankCriteria {
            get {
                return ResourceManager.GetString("TextRankCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string TextScreenFull {
            get {
                return ResourceManager.GetString("TextScreenFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Screen.
        /// </summary>
        public static string TextScreenMedium {
            get {
                return ResourceManager.GetString("TextScreenMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Screen.
        /// </summary>
        public static string TextScreenSmall {
            get {
                return ResourceManager.GetString("TextScreenSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press on player to set player&apos;s profile photo..
        /// </summary>
        public static string TextSetImage {
            get {
                return ResourceManager.GetString("TextSetImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TextSettingsTitle {
            get {
                return ResourceManager.GetString("TextSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conceded.
        /// </summary>
        public static string TextTeamConceded {
            get {
                return ResourceManager.GetString("TextTeamConceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string TextTeamDifference {
            get {
                return ResourceManager.GetString("TextTeamDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string TextTeamDraws {
            get {
                return ResourceManager.GetString("TextTeamDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string TextTeamGames {
            get {
                return ResourceManager.GetString("TextTeamGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored.
        /// </summary>
        public static string TextTeamGoals {
            get {
                return ResourceManager.GetString("TextTeamGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss.
        /// </summary>
        public static string TextTeamLoss {
            get {
                return ResourceManager.GetString("TextTeamLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Favorite Team!.
        /// </summary>
        public static string TextTeamSelector {
            get {
                return ResourceManager.GetString("TextTeamSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string TextTeamWins {
            get {
                return ResourceManager.GetString("TextTeamWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Failed!.
        /// </summary>
        public static string TextUpladFailed {
            get {
                return ResourceManager.GetString("TextUpladFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Successful..
        /// </summary>
        public static string TextUploadInfo {
            get {
                return ResourceManager.GetString("TextUploadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup Statistics Viewer.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
